name: Continuous Deployment
 
on: 
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcvTj3SHZCD8DrqxA6iUsTEOTwCN7/TMAPFPS44XlgTm1vvgFkI3Jr2mi0okEIklLdsmb0ciJKKUNsX08H5Clebvisw13XstkYyfqN3/o4kHO3sYjpVzT+sPueshSK8vSVCQvQ5DESUjd+X8ncBUG3IpHJn7ryD0fHAAwwiiKNTltY2O1Jp5sQCfDFNwareIUmBKc4GzhnY44O+IOkMsmxP7snrEt/T5Z2K+hVIo6R7kHHTKipggx/+y+/NNFjHQbn7j6h2SpTgksBOdW4JsTmRr0/oBAW/6It4GL8yK0zv2Cb9YJUp3eJp7TU4RlLkzyEW04Qz4qTcQlx8vfnx09b google-ssh
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/Forum-API-V2-Master
          git pull origin master
          npm install
          npm run migrate up
          pm2 restart forum-api