name: Continuous Deployment
 
on: 
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAtbdhH81oHSbGxjqPVFRfmNRtV8pTP3u1wClVHeyHN+fLAD7dW/U4
KKx6NMYl27esgBb8Xr6U/Zdb3NkBkWQnQU9jH68NWCJNDAgrcXJKtlqNOrTcradm62nprY
eU6msvI4GYtMlN48DDNwOopVG5iXiwNetSoT0bK6ERsMPXqYmu1FHcMHGwYZzrHrtRPBHy
mEHL966Bjnmb/1LSN9y7kP5CEqd3NRUJPcmNhswNMeeelaXB9oGGS8lhg8NJW4pD2MOBah
ULlrKeCeMFXBhfpEqMYgayGJWTVMlpT5oa1oRCFUpZZui4YZ71YDkZylGzk56YTrouYcu+
QcMQjUTo0oOJUBcPWzd0sI46iVcGTamN9ccWnhIslppIrQVObu3YdINUFQLBddV85tjeup
53lqrowbi3hdS2CelCMhKo2dN31muFcZ9UWCzRZI2g/D+DGEsmkXQ+2SmGC/tewVf0pCY5
jZnfzhCmEHc/hug/4sBYdmFEDMzrNOT/4DJgsZvVAAAFmNGCRPHRgkTxAAAAB3NzaC1yc2
EAAAGBALW3YR/NaB0mxsY6j1RUX5jUbVfKUz97tcApVR3shzfnywA+3Vv1OCisejTGJdu3
rIAW/F6+lP2XW9zZAZFkJ0FPYx+vDVgiTQwIK3FySrZajTq03K2nZutp6a2HlOprLyOBmL
TJTePAwzcDqKVRuYl4sDXrUqE9GyuhEbDD16mJrtRR3DBxsGGc6x67UTwR8phBy/eugY55
m/9S0jfcu5D+QhKndzUVCT3JjYbMDTHnnpWlwfaBhkvJYYPDSVuKQ9jDgWoVC5ayngnjBV
wYX6RKjGIGshiVk1TJaU+aGtaEQhVKWWbouGGe9WA5GcpRs5OemE66LmHLvkHDEI1E6NKD
iVAXD1s3dLCOOolXBk2pjfXHFp4SLJaaSK0FTm7t2HSDVBUCwXXVfObY3rqed5aq6MG4t4
XUtgnpQjISqNnTd9ZrhXGfVFgs0WSNoPw/gxhLJpF0Ptkphgv7XsFX9KQmOY2Z384QphB3
P4boP+LAWHZhRAzM6zTk/+AyYLGb1QAAAAMBAAEAAAGACQDH6Bp2MRONv56BIW14uwqzTC
kzDK8lZxrlI7FnVaa/UQjMUNUKbkF1YI38rDEic8ovwMXyfcn0/DEoObrbkwnK4HP81kQE
yzbQaDOAbh54ZtM1J8lmeP1rXXSdNSwQTtMJ7NMYb9NKGLyuq1osNhprqJA7LM/pO7UkOj
zJv5WZut0/aosHcR6kK4aeVLqS6WZBI8lak+OEjhbdYXUnOdzPCzuO1WtwZMZKo8YSVUmj
esiWno72R2T31t5jEQz9kCzZUXsOVAZfQIUISG/ejeU+mObVno8DQ7iEa5YDNo2U0u9TLt
Bukm4dXxTJ/PPncSefWHBRAnI13IRyJaJIpdLnIREk5heJx6FhnO+atmydXkfZM0F1PnnN
QhfVvD4kg7mO3QPWiK5EKIfuDm/ekEHvSgOOHnhmC1a29DitG3o8CxeKVZ/4PSok/Xof6r
9wbrD4ANnCToNqgN3bdIwLcSrGCvSV0ZDPePfqAGbbU/SnfzxH+vagCGNIG4vbLKABAAAA
wAM65f+GgFRN8AMpF9LxBFtAIa5mGpc9zjJGMiekHbK3uIcI1gkxDEXXKSJriJNkOVPy1H
QcwvTkoXJduGBnKBcTX/3IN6gT6saDg5r6yzQ0IPamy4fyg3iSmBYmgWywQ/uByyGAFnsh
acYQH8U4ei0zlvruABZf5NK/vkJ0cZDRGeqy5Chjt8Hb3/oibutSO+O+0nIRYqSermihxf
vzjNf3jNoC1Mft1iaBEt2c72az3rJrMQoie6cOUV15achCmwAAAMEA2wY7J/E1ddUUtXa+
pKeRgEMuyp2CkwieqswsyMK1n1a/P9Aqx4zVi6/fu9OeWcRdBINl047PhfihQ+a7N36d3q
VhCVXS5Wwe3Djc+eIoSpOI+iV3hTzGyUuav1pb6JeODJGl28wuHMP0v5wwHuYuC0hrDUZO
gnFew3ZYjfjke0rfObW5cDQhTN14Wp3QSkYrSIzcc5McYgRh2Gtgb1w+WWkmt6slpX8L1R
HhpSaoDLP9pN/WobKGBlvLMA/164PVAAAAwQDUZMZZw1lQqtG3HFiTomXFv+VYii3p8guM
mSzAC+uEibn7i9VcxI7NDKp6/eDZ0I8ptdiEf9qUnOyu1jXKvf3+jAH2KCCwaxRMZaqkka
waUY/AzFDgpWwdVA/HlGl9wL8aR2oPDmbXEuKFrsyKEKtMbfV4TYBtY8X9dc6GP6oGH+6G
MbPyGXNykBCc46R5kum83lLNt0HSs9gYuk5kUGOmGXW5lCfQ2Ms12LcG+xcaFx7UC8czPD
gBGSHbvKdxuAEAAAAdYWRtaW5pc3RyYXRvckBXSU4tSjhRTVVLTzlLMk0BAgMEBQY=
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/Forum-API-V2-Master
          git pull origin master
          npm install
          npm run migrate up
          pm2 restart forum-api
